import 'dart:convert';
import 'dart:io';

Future<void> main(List<String> args) async {
  if (args.length < 2) {
    stderr.writeln(
      'Usage: dart run tool/flutter_env.dart <development|production|file.json> <run|build|test|prepare> [Flutter arguments]',
    );
    exitCode = 64;
    return;
  }
  try {
    if (!['run', 'build', 'test', 'prepare'].contains(args[1])) {
      throw const FormatException(
        'Supported commands: run, build, test, prepare',
      );
    }
    if (args.skip(2).any((arg) => arg.startsWith('--dart-define'))) {
      throw const FormatException(
        'Manage Dart defines in the environment JSON file so native settings stay synchronized',
      );
    }
    final root = File.fromUri(Platform.script).parent.parent;
    final file = File(
      args.first.endsWith('.json')
          ? args.first
          : '${root.path}/config/env/${args.first}.json',
    ).absolute;
    final config =
        jsonDecode(await file.readAsString()) as Map<String, dynamic>;
    const requiredKeys = [
      'APP_ENV',
      'API_BASE_URL',
      'AGENT_API_BASE_URL',
      'WECHAT_APP_ID',
      'WECHAT_UNIVERSAL_LINK',
      'USER_AGREEMENT_URL',
      'PRIVACY_POLICY_URL',
    ];
    for (final key in requiredKeys) {
      if (config[key] is! String || (config[key] as String).trim().isEmpty) {
        throw FormatException('Missing or invalid $key');
      }
    }
    if (config['API_ENABLE_LOGGING'] is! bool) {
      throw const FormatException('API_ENABLE_LOGGING must be a boolean');
    }
    for (final key in [
      'API_BASE_URL',
      'AGENT_API_BASE_URL',
      'WECHAT_UNIVERSAL_LINK',
      'USER_AGREEMENT_URL',
      'PRIVACY_POLICY_URL',
    ]) {
      final uri = Uri.parse(config[key] as String);
      if (!uri.hasAuthority || !['https', 'http'].contains(uri.scheme)) {
        throw FormatException('$key must be an HTTP(S) URL');
      }
    }
    final configuredAgentOrigin = config['AGENT_API_ORIGIN'] ?? '';
    if (configuredAgentOrigin is! String) {
      throw const FormatException('AGENT_API_ORIGIN must be a string');
    }
    if (configuredAgentOrigin.isNotEmpty) {
      final agentOrigin = Uri.parse(configuredAgentOrigin);
      if (!agentOrigin.hasAuthority ||
          !['https', 'http'].contains(agentOrigin.scheme) ||
          configuredAgentOrigin != agentOrigin.origin) {
        throw const FormatException(
          'AGENT_API_ORIGIN must be an HTTP(S) origin without a path',
        );
      }
    }
    final appId = config['WECHAT_APP_ID'] as String;
    if (!RegExp(r'^wx[a-zA-Z0-9]+$').hasMatch(appId)) {
      throw const FormatException('Invalid WECHAT_APP_ID');
    }
    final link = Uri.parse(config['WECHAT_UNIVERSAL_LINK'] as String);
    if (link.scheme != 'https' ||
        !RegExp(r'^[a-zA-Z0-9.-]+$').hasMatch(link.host)) {
      throw const FormatException(
        'WECHAT_UNIVERSAL_LINK requires an HTTPS domain',
      );
    }
    final douyinClientKey = config['DOUYIN_CLIENT_KEY'] ?? '';
    if (douyinClientKey is! String ||
        (douyinClientKey.isNotEmpty &&
            !RegExp(r'^[a-zA-Z0-9]+$').hasMatch(douyinClientKey))) {
      throw const FormatException('Invalid DOUYIN_CLIENT_KEY');
    }
    final douyinLink = Uri.parse(
      config['DOUYIN_UNIVERSAL_LINK'] as String? ??
          config['WECHAT_UNIVERSAL_LINK'] as String,
    );
    if (douyinLink.scheme != 'https' ||
        !RegExp(r'^[a-zA-Z0-9.-]+$').hasMatch(douyinLink.host)) {
      throw const FormatException(
        'DOUYIN_UNIVERSAL_LINK requires an HTTPS domain',
      );
    }
    // Native iOS settings must use the same values as Dart's compile-time defines.
    await File('${root.path}/ios/Flutter/Environment.xcconfig').writeAsString(
      '// Generated by tool/flutter_env.dart.\n'
      'WECHAT_APP_ID = $appId\n'
      'WECHAT_ASSOCIATED_DOMAIN = ${link.host}\n'
      'DOUYIN_CLIENT_KEY = $douyinClientKey\n'
      'DOUYIN_ASSOCIATED_DOMAIN = ${douyinLink.host}\n'
      'DOUYIN_UNIVERSAL_LINK = ${douyinLink.toString().replaceFirst('://', ':/'
          r'$()'
          '/')}\n',
    );
    stdout.writeln('Environment: ${config['APP_ENV']} (${file.path})');
    if (args[1] == 'prepare') return;
    final process = await Process.start(
      'flutter',
      [args[1], ...args.skip(2), '--dart-define-from-file=${file.path}'],
      workingDirectory: root.path,
      mode: ProcessStartMode.inheritStdio,
    );
    exitCode = await process.exitCode;
  } catch (error) {
    stderr.writeln('Environment configuration failed: $error');
    exitCode = 1;
  }
}
